# fullstack frontend .gitpod.yml
# multi-repo
additionalRepositories:
  - url: https://github.com/doitian/guidepost-ghost
    checkoutLocation: guidepost-ghost

checkoutLocation: iany.me

tasks:
  - name: blog
    before: brew install hugo
    init: hugo version
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

  - name: theme
    before: |
      cd ../guidepost-ghost
    init: |
      npm install
    command: |
      gulp watch

workspaceLocation: mirror-iany.me/.vscode/fullstack.code-workspace
