baseURL = "https://blog.iany.me/"
locale = "en-US"
label = "English"
defaultContentLanguage = "en"
hasCJKLanguage = false
theme = "guidepost"
copyright = '<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>'
footnoteReturnLinkContents = "↩︎"
summaryLength = 33
enableGitInfo = true
disableHugoGeneratorInject = true

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[permalinks]
post = "/:year/:month/:contentbasename/"
life = "/life/:year/:month/:contentbasename/"
game = "/games/:year/:month/:contentbasename/"
journal = "/journal/:year/:month/:contentbasename/"

[taxonomies]
tag = "tags"
series = "series"

[related]
includeNewer = true
[[related.indices]]
name = "series"
weight = 200
[[related.indices]]
name = "tags"
weight = 150
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name = "date"
weight = 10

[frontmatter]
date = [":default", ":git", ":fileModTime"]
publishDate = [":default", ":git", ":fileModTime"]

[imaging]
resampleFilter = "box"
quality = 75
anchor = "smart"

[params]
gcse = '006252023667590608831:yopsgewhz5y'
mainSections = ["post", "game"]
# URL prefix for "view source" link (post markdown in GitHub).
sourceLinkPrefix = "https://github.com/doitian/mirror-iany.me/blob/master/content/"
# disqusBaseURL = "https://blog.iany.me/"

[params.listing]
post = 12
journal = 3

[params.Author]
name = "Ian Yang"
avatar = "/avatar-96x96.png"
givenName = "Ian"
familyName = "Yang"
email = "me@iany.me"

[params.Author.social]
github = "doitian"
twitter = "doitian"
raindrop = "doitian"

[languages]
[languages.en]
title = "~iany/"
locale = "en-US"
hasCJKLanguage = false
label = "English"
weight = 10
# disqusUsername = "ianyblog"

[[languages.en.menu.main]]
identifier = "series"
name = "Series"
title = "Articles in Series"
url = "/series/"
weight = 2

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 3

[[languages.en.menu.social]]
identifier = "about"
pre = '<i aria-hidden="true" class="fas fa-user-circle"></i>'
url = "/about/"
name = "About Me"
title = "About Me"

[[languages.en.menu.social]]
identifier = "email"
pre = '<i aria-hidden="true" class="fas fa-envelope"></i>'
url = "https://u.iany.me/gpg"
name = "Email"
title = "Email"

[languages.zh]
title = "~iany/"
locale = "zh-CN"
hasCJKLanguage = true
label = "中文"
weight = 20
# disqusUsername = "ianyblogcn"

[[languages.zh.menu.main]]
identifier = "series"
name = "系列"
title = "系列文章"
url = "/zh/series/"
weight = 2

[[languages.zh.menu.main]]
identifier = "tags"
name = "标签"
title = "标签"
url = "/zh/tags/"
weight = 3

[[languages.zh.menu.social]]
identifier = "about"
pre = '<i aria-hidden="true" class="fas fa-user-circle"></i>'
url = "/zh/about/"
name = "关于"
title = "关于作者"

[[languages.zh.menu.social]]
identifier = "email"
pre = '<i aria-hidden="true" class="fas fa-envelope"></i>'
url = "https://u.iany.me/gpg"
name = "邮件"
title = "邮件"
